name: Clean History

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date to clean (YYYY-MM-DD)"
        required: true
        type: string
      dry_run:
        description: "Preview changes without executing"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need full history to clean it
          fetch-depth: 0
          # Work directly on the default branch
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "${{ vars.GRAPH_AUTHOR_NAME }}"
          git config user.email "${{ vars.GRAPH_AUTHOR_EMAIL }}"

      - name: Clean history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATE: ${{ inputs.date }}
          DRY_RUN: ${{ inputs.dry_run && '1' || '0' }}
        run: |
          # Validate date format
          if ! [[ "$DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            echo "Error: Invalid date format. Use YYYY-MM-DD" >&2
            exit 1
          fi

          # Authenticate remote for pushes
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

          # Run the cleanup script
          chmod +x scripts/clean-history.sh
          ./scripts/clean-history.sh --date "$DATE" ${DRY_RUN:+--dry-run}

          # Only push if this wasn't a dry run
          if [ "$DRY_RUN" = "0" ]; then
            echo "Pushing changes..."
            git push -f origin "${{ github.event.repository.default_branch }}"
          fi
